### ISSUE TITLE
matching cuda version to Pytorch version

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#297]
Hello,

I'm using Linux Ubuntu 20.04, with python 3.8, Nvidia GeForce RTX 3070 and cuda version 11.4. I've installed aihwkit version 0.4.0, which requires PyTorch 1.8.1, and when running some of the git examples, I get the following error:

`aihwkit_env/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning:
NVIDIA GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "./03_mnist_training.py", line 206, in <module>
    main()
  File "./03_mnist_training.py", line 195, in main
    model = create_analog_network(INPUT_SIZE, HIDDEN_SIZES, OUTPUT_SIZE)
  File "./03_mnist_training.py", line 98, in create_analog_network
    model.cuda()
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/aihwkit/nn/modules/container.py", line 71, in cuda
    super().cuda(device)
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/aihwkit/optim/context.py", line 80, in cuda
    self.analog_tile = self.analog_tile.cuda(device)
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/aihwkit/simulator/tiles/analog.py", line 238, in cuda
    raise CudaError('aihwkit has not been compiled with CUDA support')
aihwkit.exceptions.CudaError: aihwkit has not been compiled with CUDA support
`

since the kit specifically requires for this pytorch version, I'd be grateful if you could specify which cuda version is required? I've tried looking online, but couldn't find the adequate cuda version for pytorch 1.8.1

thank you.

**Comment by maljoras** [comment]
Hi @ElinorG11,

you can try to compile the AIHWKIT with the newest pytorch version.  We had some issues with pytorch 1.9 in the past, but as far as I know, these should be removed. I was able to compile and run it with pytorch 1.10 without any issues. We will updated the requirements once we have more testing. However, I found that CUDA 11.4 together with NVIDIA T2000 might have some issues, but e.g. 11.3 with V100 works flawlessly. So if you get any CUBLAS errors, you might considering using CUDA 11.3. 

Hope that helps.

**Comment by maljoras** [comment]
But also note that you are running the pip version of aihwkit, which has not been compiled for CUDA. You need to compile it  first. You error above  has nothing to do with the pytorch / CUDA version. As of now we do not have cuda precompiled packages with pip. You need to clone the repository and do the developer install with `-DUSE_CUDA=ON`, as described in the documentation.

**Comment by ElinorG11** [comment]
I had clashing between `aihwkit` versions - the one installed with pip and the one compiled with cuda. Once I've properly installed and compiled single version with cuda the error no longer appears. Thank you very much for your help.

**Comment by maljoras** [comment]
Great that it worked!
