### ISSUE TITLE
Memory consumed by example 18_cifar10_on_resnet.py

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#299]
Hello,

I'm working on Linux Ubuntu 20.04 with Nvidia RTX 3070 and cuda 11.3 version. When running the specific example `18_cifar10_on_resnet.py` I get the following error:

```
15:19:17 --- Started ResNet Training
Traceback (most recent call last):
  File "./18_cifar10_on_resnet.py", line 321, in <module>
    main()
  File "./18_cifar10_on_resnet.py", line 310, in main
    model, optimizer = training_loop(model, criterion, optimizer, train_data, validation_data,
  File "./18_cifar10_on_resnet.py", line 262, in training_loop
    model, optimizer, train_loss = train_step(train_data, model, criterion, optimizer)
  File "./18_cifar10_on_resnet.py", line 196, in train_step
    optimizer.step()
  File "/home/elinor/aihwkit_env/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/elinor/aihwkit/src/aihwkit/optim/analog_optimizer.py", line 108, in step
    analog_tile.update_indexed(x_input, d_input)
  File "/home/elinor/aihwkit/src/aihwkit/simulator/tiles/base.py", line 786, in update_indexed
    return self.tile.update_indexed(x_input, d_input)

RuntimeError: CUDA_CALL Error 'out of memory' at cuda_util.cu:660
```

I have ~8GB on my GPU. How much memory does this example consumes?

Thank you

**Comment by maljoras** [comment]
Hi @ElinorG11 ,
yes, that could be. We are typically using V100 GPUs which have 32GB of memory, where the example runs fine as is.  ML workloads are unfortunately quite memory hungry and the analog simulations need additional memory compared to standard DNNs. However, a simple solution to reduce the memory footprint is to reduce the batch size of 128 to e.g. 64. That will almost half the memory usage without any impact on accuracy (just the runtime might be somewhat longer because GPUs tend to run more efficient for larger batch size). In fact, accuracy might even improve as typically learning is improved with somewhat smaller batch sizes. Only the learning rate might need to be adapted (e.g. halved when batchsize is halved).
