### ISSUE TITLE
Issue with development setup

### ISSUE THREAD

**Issue by amir-parvaresh** [IBM/aihwkit#477]
## Description

Dear Developers,
I wanted to compile the rpucuda on my system and I get the following error:
Traceback (most recent call last):
  File "C:\Users\aparvare\IdeaProjects\aihwkit\examples\12_simple_layer_with_mixed_precision.py", line 25, in <module>
    from aihwkit.nn import AnalogLinear
  File "C:\Users\aparvare\IdeaProjects\aihwkit\src\aihwkit\nn\__init__.py", line 17, in <module>
    from aihwkit.nn.modules.container import AnalogSequential
  File "C:\Users\aparvare\IdeaProjects\aihwkit\src\aihwkit\nn\modules\container.py", line 24, in <module>
    from aihwkit.nn.modules.base import AnalogModuleBase
  File "C:\Users\aparvare\IdeaProjects\aihwkit\src\aihwkit\nn\modules\base.py", line 26, in <module>
    from aihwkit.simulator.configs.configs import (
  File "C:\Users\aparvare\IdeaProjects\aihwkit\src\aihwkit\simulator\configs\__init__.py", line 15, in <module>
    from .configs import (
  File "C:\Users\aparvare\IdeaProjects\aihwkit\src\aihwkit\simulator\configs\configs.py", line 18, in <module>
    from aihwkit.simulator.configs.devices import (
  File "C:\Users\aparvare\IdeaProjects\aihwkit\src\aihwkit\simulator\configs\devices.py", line 24, in <module>
    from aihwkit.simulator.configs.helpers import (
  File "C:\Users\aparvare\IdeaProjects\aihwkit\src\aihwkit\simulator\configs\helpers.py", line 20, in <module>
    from aihwkit.simulator.rpu_base import devices, tiles
ModuleNotFoundError: No module named 'aihwkit.simulator.rpu_base'

it seems that the aihwkit.simulator.rpu_base is missing. I have also checked the git repo and there was no such directory. I would appreciate if you could help me in this regard. The rpucuda is already compiled.
Best regards,
Amir

* Pytorch version: 1.13.1+cu116
* Package version: latest
* OS: Windows 10
* Python version: 3.10
* Conda version (or N/A): N/A

**Comment by maljoras** [comment]
Hi @amir-parvaresh,
the `rpu_base` is a library that will get generated once you compiled the code. If you use the `--inplace` flag then it will be put into the directory where the github clone reside. Otherwise it will be copied to the site-package directory. So it is important to set the `PYTHONPATH` correctly to either of these directories. If you cannot fine the library, the compilation was not  successful.

**Comment by amir-parvaresh** [comment]
Thank you so much for the information.
I have an other question: Is there any way I can trace the RPUCUDA code, before the compilation. I am trying to undrestand the rpucuda code, but the development setup guide described in the documentation, compiles the it and use it as a library.
Thanks in advance :)

**Comment by maljoras** [comment]
You can just look at the source code in the `src/rpucuda` directory. You can trace it with typical C++ tools like `gdb`
