### ISSUE TITLE
I was trying to install aihwkit on windows using pip, but it gives error

### ISSUE THREAD

**Issue by patrick-chen-98** [IBM/aihwkit#483]
## Description

I used "pip install aihwkit" to install the package, and**### the installation gives me the folling error:**

Building wheels for collected packages: aihwkit
  Building wheel for aihwkit (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [164 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 17 2022

        could not find any instance of Visual Studio.

      -- Configuring incomplete, errors occurred!
      See also "C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.29.30148.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.29.30148.0
      CMake Warning (dev) at C:/Users/patrick/AppData/Local/Programs/Python/Python39/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/patrick/AppData/Local/Programs/Python/Python39/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-build
        Command:
          'C:\Users\patrick\AppData\Local\Programs\Python\Python39\Scripts\cmake.EXE' 'C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.9.13 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\patrick\anaconda3\lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\patrick\anaconda3\libs\python39.lib' '-DPython_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython3_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is MSVC 19.29.30148.0
      -- The CXX compiler identification is MSVC 19.29.30148.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Invoking cmake through scikit-build
      -- The BLAS backend of choice:OpenBLAS
      -- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
      -- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
      CMake Error at cmake/Modules/FindOpenBLAS.cmake:89 (MESSAGE):
        Could not find OpenBLAS
      Call Stack (most recent call first):
        cmake/dependencies.cmake:56 (find_package)
        CMakeLists.txt:39 (include)

      -- Configuring incomplete, errors occurred!
      See also "C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_skbuild/win-amd64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "C:\Users\patrick\anaconda3\lib\site-packages\skbuild\setuptools_wrap.py", line 634, in setup
          env = cmkr.configure(
        File "C:\Users\patrick\anaconda3\lib\site-packages\skbuild\cmaker.py", line 332, in configure
          raise SKBuildError(

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\patrick\AppData\Local\Programs\Python\Python39\Scripts\cmake.EXE' 'C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.9.13 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\patrick\anaconda3\lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\patrick\anaconda3\libs\python39.lib' '-DPython_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython3_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06
        Working directory:
          C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aihwkit
  Running setup.py clean for aihwkit
Failed to build aihwkit
Installing collected packages: aihwkit
  Running setup.py install for aihwkit ... error
  error: subprocess-exited-with-error

  × Running setup.py install for aihwkit did not run successfully.
  │ exit code: 1
  ╰─> [166 lines of output]
      C:\Users\patrick\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 17 2022

        could not find any instance of Visual Studio.

      -- Configuring incomplete, errors occurred!
      See also "C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.29.30148.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.29.30148.0
      CMake Warning (dev) at C:/Users/patrick/AppData/Local/Programs/Python/Python39/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/patrick/AppData/Local/Programs/Python/Python39/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-build
        Command:
          'C:\Users\patrick\AppData\Local\Programs\Python\Python39\Scripts\cmake.EXE' 'C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.9.13 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\patrick\anaconda3\lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\patrick\anaconda3\libs\python39.lib' '-DPython_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython3_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is MSVC 19.29.30148.0
      -- The CXX compiler identification is MSVC 19.29.30148.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Invoking cmake through scikit-build
      -- The BLAS backend of choice:OpenBLAS
      -- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
      -- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
      CMake Error at cmake/Modules/FindOpenBLAS.cmake:89 (MESSAGE):
        Could not find OpenBLAS
      Call Stack (most recent call first):
        cmake/dependencies.cmake:56 (find_package)
        CMakeLists.txt:39 (include)

      -- Configuring incomplete, errors occurred!
      See also "C:/Users/patrick/AppData/Local/Temp/pip-install-c94h9dk2/aihwkit_eb93954004ef47fdae05f3c35fe60a06/_skbuild/win-amd64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "C:\Users\patrick\anaconda3\lib\site-packages\skbuild\setuptools_wrap.py", line 634, in setup
          env = cmkr.configure(
        File "C:\Users\patrick\anaconda3\lib\site-packages\skbuild\cmaker.py", line 332, in configure
          raise SKBuildError(

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\patrick\AppData\Local\Programs\Python\Python39\Scripts\cmake.EXE' 'C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.9.13 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\patrick\anaconda3\lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\patrick\anaconda3\libs\python39.lib' '-DPython_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Users\patrick\anaconda3\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\patrick\anaconda3' '-DPython3_INCLUDE_DIR:PATH=C:\Users\patrick\anaconda3\Include' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Users\patrick\anaconda3\lib\site-packages\numpy\core\include' -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06
        Working directory:
          C:\Users\patrick\AppData\Local\Temp\pip-install-c94h9dk2\aihwkit_eb93954004ef47fdae05f3c35fe60a06\_skbuild\win-amd64-3.9\cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> aihwkit

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

* Pytorch version: 1.10.0+cu113
* Package version: I just used "pip install aihwkit", I don't know the version
* OS: windows 11 22H2
* Python version: 3.9.13
* Conda version (or N/A): 23.1.0

**Comment by maljoras** [comment]
Hi @patrick-chen-98,
you need to install either the OpenBLAS or MKL library. Please consult the [installation instructions](https://aihwkit.readthedocs.io/en/latest/advanced_install.html#windows-using-conda-experimental).
