### ISSUE TITLE
Fail to install aihwkit on mac

### ISSUE THREAD

**Issue by Zhaoxian-Wu** [IBM/aihwkit#541]
## Description

I'm try to install aihwkit on mac, but it fails.

## How to reproduce

Type the following command in the terminal.
```
pip install aihwkit
```
and it reports that
```\wangbudong@wangbudongs-Mac-mini 2023.09.05 analog % pip install aihwkit
Collecting aihwkit
  Downloading aihwkit-0.8.0.tar.gz (557 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.2/557.2 kB 29.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/1q/grd7t3p519x86dj503y565lr0000gn/T/pip-install-dw_r2s1t/aihwkit_59886bc9f95a497cb03319c3f0a6021f/setup.py", line 18, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Expected behavior

Get aihwkit installed

## Other information

* Pytorch version: 3.11.5
* Package version: 0.8.0
* OS: macOS Ventura 13.5.2
* Python version:3.11.5
* Pip version: 23.2.1
* Conda version (or N/A): No

**Comment by Zhaoxian-Wu** [comment]
Thanks for your reply @maljoras! Following your suggestion, I have successfully installed the tool kit on my device. However, I encountered another issue during the installation process (posted on [issue 541](https://github.com/IBM/aihwkit/issues/541)). Could you have a look when you are convenient?

**Comment by maljoras** [comment]
Many thanks!
