### ISSUE TITLE
WeightModifierType.DROP_CONNECT not implemented

### ISSUE THREAD

**Issue by VictorY-1Qbit** [IBM/aihwkit#622]
## Description

While training with [InferenceRPUConfig](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.configs.html#aihwkit.simulator.configs.configs.InferenceRPUConfig) and the modifier type `WeightModifierType.DROP_CONNECT`, I get a "not implemented" error.

However this option is [documented](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.parameters.enums.html#aihwkit.simulator.parameters.enums.WeightModifierType.DROP_CONNECT). It should also work with another modifier type if `pdrop>0`, which doesn't seem true. If I create a modifier as `WeightModifierParameter(type=WeightModifierType.ADD_NORMAL, std_dev=0, pdrop=0.2)` there is no error message and no drop-connect.

## How to reproduce

Based on [this example](https://github.com/IBM/aihwkit/blob/master/examples/05_simple_layer_hardware_aware.py).

```python
# pylint: disable=invalid-name

# Imports from PyTorch.
from torch import Tensor
from torch.nn.functional import mse_loss

# Imports from aihwkit.
from aihwkit.nn import AnalogLinear
from aihwkit.optim import AnalogSGD
from aihwkit.simulator.configs import (
    InferenceRPUConfig,
    WeightNoiseType,
    WeightClipType,
    WeightModifierType,
)
from aihwkit.inference import PCMLikeNoiseModel, GlobalDriftCompensation

if __name__ == '__main__':
    # Prepare the datasets (input and expected output).
    x = Tensor([[0.1, 0.2, 0.4, 0.3], [0.2, 0.1, 0.1, 0.3]])
    y = Tensor([[1.0, 0.5], [0.7, 0.3]])

    # Define a single-layer network, using inference/hardware-aware training tile
    rpu_config = InferenceRPUConfig()
    rpu_config.forward.out_res = -1.0  # Turn off (output) ADC discretization.
    rpu_config.forward.w_noise_type = WeightNoiseType.ADDITIVE_CONSTANT
    rpu_config.forward.w_noise = 0.02  # Short-term w-noise.

    rpu_config.clip.type = WeightClipType.FIXED_VALUE
    rpu_config.clip.fixed_value = 1.0
    rpu_config.modifier.pdrop = 0.1  # Drop connect
    rpu_config.modifier.type = WeightModifierType.DROP_CONNECT  # <-- Modifier type changed from the example ----
    rpu_config.modifier.rel_to_actual_wmax = True

    # Inference noise model.
    rpu_config.noise_model = PCMLikeNoiseModel(g_max=25.0)

    # drift compensation
    rpu_config.drift_compensation = GlobalDriftCompensation()

    print(rpu_config)

    model = AnalogLinear(4, 2, bias=True, rpu_config=rpu_config)

    # Define an analog-aware optimizer, preparing it for using the layers.
    opt = AnalogSGD(model.parameters(), lr=0.1)
    opt.regroup_param_groups(model)

    print(next(model.analog_tiles()).tile)

    for epoch in range(100):
        # Delete old gradient
        opt.zero_grad()
        # Add the training Tensor to the model (input).
        pred = model(x)
        # Add the expected output Tensor.
        loss = mse_loss(pred, y)
        # Run training (backward propagation).
        loss.backward()

        opt.step()

        print("Loss error: {:.16f}".format(loss))

    model.eval()

    # Do inference with drift.
    pred_before = model(x)

    print("Correct value:\t {}".format(y.detach().cpu().numpy().flatten()))
    print("Prediction after training:\t {}".format(pred_before.detach().cpu().numpy().flatten()))

    for t_inference in [0.0, 1.0, 20.0, 1000.0, 1e5]:
        model.drift_analog_weights(t_inference)
        pred_drift = model(x)
        print(
            "Prediction after drift (t={}, correction={:1.3f}):\t {}".format(
                t_inference,
                next(model.analog_tiles()).alpha.cpu().numpy(),
                pred_drift.detach().cpu().numpy().flatten(),
            )
        )
```

It gives this error message:

```
Traceback (most recent call last):
  File ".../src/debug.py", line 61, in <module>
    opt.step()
  File ".../lib/python3.9/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File ".../lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File ".../lib/python3.9/site-packages/aihwkit/optim/analog_optimizer.py", line 145, in step
    param.analog_tile.post_update_step()
  File ".../lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File ".../lib/python3.9/site-packages/aihwkit/simulator/tiles/inference.py", line 307, in post_update_step
    self.tile.modify_weights(self._tmp["weight_modify_params"])  # type: ignore
RuntimeError: Error in weight_modifier.cpp:204  Requested WeightModifierType not implemented in CPU version.
```

The message seems to imply that it is implemented with CUDA, but it is not. I get this error message:
```
...
RuntimeError: Error in weight_modifier_cuda.cu:593  Requested WeightModifierType not implemented.
```

The default exemple include `WeightModifierType.ADD_NORMAL` with a drop connect. Which doesn't apply the drop connect, according to my tests.

## Expected behavior

The `WeightModifierType.DROP_CONNECT` modifier and the `pdrop>0` with a different modifier should actually apply drop connect. 

## Other information

I might be wrong, but I think the drop connect was working with an old version of aihwkit.

* Pytorch version: 2.2.1
* Package version: 0.8 and 0.9
* OS: Linux
* Python version: 3.9.2 and 3.10.12
* Install method: with pip for CPU version and pip + [CUDA.Dockerfile](https://github.com/IBM/aihwkit/blob/master/CUDA.Dockerfile) for CUDA version

**Comment by maljoras** [comment]
Thanks @VictorY-1Qbit  for raising this issue. Looks like a check is wrong and it causes an error when it shouldn't. Indeed, drop connect was working just fine previously. Should be easy to fix though.

**Comment by jubueche** [comment]
@VictorY-1Qbit could you try again? The fix is merged into master. If it is not fixed, feel free to re-open this issue.

**Comment by VictorY-1Qbit** [comment]
I tested with with CPU and CUDA, I don't have the error anymore.
Thanks, nice work!

**Comment by Raghucharan16** [comment]
Hey @VictorY-1Qbit  I have trouble installing the libraries itself, i have this code and i tried on multiple python versions 3.6,3.7,3.8,3.9 but unable to install aihwkit,torch,torchvision 

i'm getting cmake build failed and _lzma module not found. so how can i overcome this.

```
import os
from time import time

# Imports from PyTorch.
import torch
from torch import nn
from torch.optim.lr_scheduler import StepLR
from torchvision import datasets, transforms

# Imports from aihwkit.
from aihwkit.nn import AnalogLinear, AnalogSequential
from aihwkit.optim import AnalogSGD
from aihwkit.simulator.configs import SingleRPUConfig, ConstantStepDevice
from aihwkit.simulator.rpu_base import cuda


# Check device
USE_CUDA = 0
if cuda.is_compiled():
    USE_CUDA = 1
DEVICE = torch.device("cuda" if USE_CUDA else "cpu")

# Path where the datasets will be stored.
PATH_DATASET = os.path.join("data", "DATASET")

# Network definition.
INPUT_SIZE = 784
HIDDEN_SIZES = [256, 128]
OUTPUT_SIZE = 10

# Training parameters.
EPOCHS = 30
BATCH_SIZE = 64


def load_images():
    """Load images for train from the torchvision datasets."""
    transform = transforms.Compose([transforms.ToTensor()])

    # Load the images.
    train_set = datasets.MNIST(PATH_DATASET, download=True, train=True, transform=transform)
    val_set = datasets.MNIST(PATH_DATASET, download=True, train=False, transform=transform)
    train_data = torch.utils.data.DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True)
    validation_data = torch.utils.data.DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=True)

    return train_data, validation_data


def create_analog_network(input_size, hidden_sizes, output_size):
    
    model = AnalogSequential(
        AnalogLinear(
            input_size,
            hidden_sizes[0],
            True,
            rpu_config=SingleRPUConfig(device=ConstantStepDevice()),
        ),
        nn.Sigmoid(),
        AnalogLinear(
            hidden_sizes[0],
            hidden_sizes[1],
            True,
            rpu_config=SingleRPUConfig(device=ConstantStepDevice()),
        ),
        nn.Sigmoid(),
        AnalogLinear(
            hidden_sizes[1],
            output_size,
            True,
            rpu_config=SingleRPUConfig(device=ConstantStepDevice()),
        ),
        nn.LogSoftmax(dim=1),
    )

    if USE_CUDA:
        model.cuda()

    print(model)
    return model
```
i further have code and main aim is to develop a cnn on mnist dataset.
